[package]
name = "scanner-api"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = {version = "0.5.0-rc.2", features = ["json", "uuid"]}
serde = "1"
serde_json = "1"
uuid = {version = "1", features = ["v4", "fast-rng", "serde"]}
