[package]
name = "libgcrypt-sys"
version = "0.1.0"
edition = "2021"
links = "gcrypt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libgpg-error-sys = { path = "../libgpg-error-sys" }
