name: "Build and Test"

on:
  push:
    branches: [ master, openvas-21.04, openvas-20.08, middleware ]
  pull_request:
    branches: [ master, openvas-21.04, openvas-20.08, middleware ]

jobs:
  check-format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out openvas-scanner
        uses: actions/checkout@v2
      - name: Check Source Format
        run: |
          clang-format -i -style=file src/*.{c,h} misc/*.{c,h} nasl/*.{c,h} && git diff --exit-code
  gen_xml_doc:
    name: Build XML documentation
    runs-on: ubuntu-latest
    container: greenbone/code-metrics-doxygen-debian-stretch
    steps:
      - name: Check out openvas-scanner
        uses: actions/checkout@v2
      - name: Generate documentation (XML)
        run: |
             mkdir build && cd build/ && cmake -DSKIP_SRC=1 .. \
             && make doc-xml 2> ~/doxygen-stderr.txt
      - name: Upload doxygen error output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: doxygen-stderr.txt
          path: ~/doxygen-stderr.txt
      - name: Upload XML documentation as artifact
        uses: actions/upload-artifact@v2
        with:
          name: xml-doc
          path: build/doc/generated/xml/

  doc-coverage:
    name: Upload doc coverage to Codecov
    needs: gen_xml_doc
    runs-on: ubuntu-latest
    container: greenbone/openvas-scanner-middleware-clang-testing
    steps:
      - name: Check out openvas-scanner
        uses: actions/checkout@v2
      - name: Install coverxygen and codecov
        run: |
            apt-get update && apt-get --assume-yes install python3-venv curl
            python3 -m venv venv
            . venv/bin/activate
            pip install setuptools --upgrade
            pip install 'coverxygen>=1.3.1' codecov
      - name: Download XML documentation artifact
        id: xml-doc-download
        uses: actions/download-artifact@v2
        with:
          name: xml-doc
          path: /tmp/xml-doc
      - name: Establish documentation coverage
        run: |
            . venv/bin/activate
            python -m coverxygen --src-dir ${{ github.workspace }}      \
            --xml-dir ${{steps.xml-doc-download.outputs.download-path}} \
            --output lcov.info
      - uses: codecov/codecov-action@v1
        with:
          files: lcov.info

  build:
    name: Build various configs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type:
          - Debug
          - Release
        docker_base:
          - greenbone/openvas-scanner-middleware-clang-testing
          - greenbone/openvas-scanner-middleware-gcc-testing
    container: ${{ matrix.docker_base }}
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
    steps:
      - name: Check out openvas-scanner
        uses: actions/checkout@v2
      - name: Configure and compile openvas-scanner
        run: |
          mkdir build && cd build/ &&                \
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && \
          make install

  scan-build:
    name: Scan-build (clang static analyzer)
    runs-on: ubuntu-latest
    container: greenbone/openvas-scanner-middleware-clang-testing
    steps:
      - name: Check out openvas-scanner
        uses: actions/checkout@v2
      - name: Configure and Scan Build
        run: |
          mkdir build && cd build/ &&                      \
          scan-build cmake -DCMAKE_BUILD_TYPE=Release .. &&  \
          scan-build -o ~/scan-build-report make
      - name: Upload scan-build report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: scan-build-report
          path: ~/scan-build-report/

  test-units:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    container: greenbone/openvas-scanner-middleware-gcc-testing
    steps:
      - name: Check out openvas-scanner
        uses: actions/checkout@v2
      - name: Configure and run unit tests
        run: |
          mkdir build && cd build/ &&             \
          cmake -DCMAKE_BUILD_TYPE=Release .. &&  \
          make tests && CTEST_OUTPUT_ON_FAILURE=1 make test
