name: Build and upload docker images

on:
  push:
    branches: [ main, stable, oldstable, middleware ]

jobs:
  upload-testing:
    name: "Upload testing docker images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find reference branch
        run: |
          echo $GITHUB_BASE_REF
          echo $GITHUB_REF
          if [ -n "$GITHUB_BASE_REF" ];                              \
          then echo "VERSION=${GITHUB_BASE_REF##*/}" >> $GITHUB_ENV;  \
          else echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV;       \
          fi;                                                        \
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # this only works with github.ref on push not on pull_request. ;)
      - run: echo "Build and push ${{ github.repository }}-${{ matrix.compiler }}-testing:${{ matrix.branches }}"
      - name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: ${{ github.repository }}-${{ matrix.compiler }}-testing:${{ matrix.branches }}
          file: .docker/testing/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            COMPILER=${{ matrix.compiler }}

  upload-build:
    needs: upload-testing
    name: "Upload build docker images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find reference branch
        run: |
          echo $GITHUB_BASE_REF
          echo $GITHUB_REF
          if [ -n "$GITHUB_BASE_REF" ];                              \
          then echo "VERSION=${GITHUB_BASE_REF##*/}" >> $GITHUB_ENV;  \
          else echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV;       \
          fi;                                                        \
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # this only works with github.ref on push not on pull_request. ;)
      - run: echo "Build and push ${{ github.repository }}-${{ matrix.compiler }}-build:${{ matrix.branches }}"
      - name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: ${{ github.repository }}-${{ matrix.compiler }}-build:${{ matrix.branches }}
          file: .docker/build/Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            COMPILER=${{ matrix.compiler }}
