name: "Helm Push"

on: [workflow_call]

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: greenbone/actions/helm-build-push@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          chart-name: openvasd
          registry: ${{ vars.IMAGE_REGISTRY }}
          registry-subpath: helm-charts/
          registry-user: ${{ secrets.GREENBONE_BOT }}
          registry-token: ${{ secrets.GREENBONE_BOT_PACKAGES_WRITE_TOKEN }}
